name: dealflow_ai_engine
version: 1.0.0
profile: dealflow_ai_engine
config-version: 2

model-paths: ["models"]

models:
  dealflow_ai_engine:
    staging:
      +materialized: view
    marts:
      +materialized: table
